name: iAuction
main: org.rob4001.iAuction.iAuction
version: 3.6
author: Rob4001 forked by vanZeben
description: Auctions for iConomy plugin for Bukkit Original by Zazara107

commands:
  auction:
    aliases: [au]