name: iAuction
main: org.rob4001.iAuction.iAuction
version: 3.5
author: Rob4001
description: Auctions for iConomy plugin for Bukkit Original by Zazara107
commands:
  auction:
    description: Manages auctions
    usage: /<command> help - show auctions help